### ISSUE TITLE
Getting my domain flagged

### ISSUE THREAD

**Issue by whithey79** [muraenateam/muraena#101]
How can I activate a captcha (like cloudflare turnstile) so my domain doesn’t get flagged

**Comment by ohpe** [comment]
This is not supported, not even the main goal of muraena.

**Comment by whithey79** [comment]
I totally get it @ohpe 
Thing is I had it setup few days ago and had my domain flagged as phishing. Is there anyway I can bypass getting my domain detected/flagged?

**Comment by ohpe** [comment]
I'm sorry but I can't help.
