### ISSUE TITLE
Feature request: allow multiple configurations

### ISSUE THREAD

**Issue by JuxhinDB** [muraenateam/muraena#11]
Hey there, 

I've been playing around with the existing setup and got things to run nicely. One thing I'm not sure about (particularly when contrasting with EvilGinx2), is the use of multiple configs/phishlets on a single binding. 

Is it possible to have Muraena bind on 80/443 and configured to handle multiple domains at the same time?

**Comment by ohpe** [comment]
At the moment we do not support multiple configurations. One thing you might do is to add the domains you want to handle in the config. 
But I agree it might be a nice additional feature.

**Comment by JuxhinDB** [comment]
Great, thanks for clarifying @ohpe.

**Comment by SomeKirill** [comment]
Can't we use different ports for different instances of muraena to proxy it later via nginx or something? If so, can I specify that I don't want to proxy port to target site?

**Comment by ohpe** [comment]
I'm not sure I got your question @SomeKirill, the latest commit in muraena allows to configure the listening ip/port. See the config here:
https://github.com/muraenateam/muraena/blob/master/config/config.json#L6

**Comment by SomeKirill** [comment]
> I'm not sure I got your question @SomeKirill, the latest commit in muraena allows to configure the listening ip/port. See the config here:
> https://github.com/muraenateam/muraena/blob/master/config/config.json#L6

Here what I mean. If I listen port 1443, it will be forwarded to target server and as result, no request will be performed.
![image](https://user-images.githubusercontent.com/68379446/98990324-fd1c1280-2532-11eb-8c26-550b4acb86c1.png)

**Comment by ohpe** [comment]
Ah gotcha, yes that was the intended way. But I'll add an extra option to do portmapping.

**Comment by antisnatchor** [comment]
In general, you can easily front Muraena with Nginx, if really needed. 
Just use the standard proxy directives.
