### ISSUE TITLE
base64 transform does not work

### ISSUE THREAD

**Issue by jaredxx1** [muraenateam/muraena#12]
Hello guys,

First of all, congratulations on your project! It's really cool. I've watched your presentation.
However, I have an issue. Can't get this done right. Due to lack of documentation, I have to ask here.
It seems that there is no substitution for the domain in the recaptcha url on my side. I'm not sure why and I'll need some hints.

The changes I made to the config are minimal.

Here is my config. I would like to understand why the substitution does not happen.

[config.txt](https://github.com/muraenateam/muraena/files/3281826/config.txt)

Expected result: https://www.google.com/recaptcha/api2/anchor?ar=1&k=6Ld2sf4SAAAAAKSgzs0Q13IZhY02Pyo31S2jgOB5&co=aHR0cHM6Ly9wYXRyaWNraGxhdWtlLmdpdGh1Yi5pbzo0NDM.&hl=en&v=v1559543665173&size=normal&cb=u5a2kfjvnq1x

What I get: https://www6.ouard.com/recaptcha/api2/anchor?ar=1&amp;k=6Ld2sf4SAAAAAKSgzs0Q13IZhY02Pyo31S2jgOB5&amp;co=aHR0cHM6Ly9vdWFyZC5jb206NDQz&amp;hl=en&amp;v=v1559543665173&amp;size=normal&amp;cb=v2wy1je7i74l

As you can see, the value of the co variable from the url is pointing at my domain.

**Comment by jaredxx1** [comment]
I found another issue. I was trying to understand what I am doing wrong and found that some sites have two dots instead of one after the base64 value.

Example: k=111&co=222..&hl=en

If I use the following format it does not work.

"transform": {
      "base64": {
        "enabled": true,
        "padding": [
          "=",
          ".."
        ]
2019-06-12 17:12:43 dbg: Invalid Base64 padding value [..], falling back to =

I've tried these methods so far: "\u002E", "\u002E\u002E", even the ampersand/and sign "\&", "\u0026".

**Comment by ohpe** [comment]
Hi, in base64 you can have at the end of the encoded string one or two padding characters.
Usually it's the equal, but in some URL-based protocols the `=` is replaced with a `.`.
You just have to identify the padding characters in the config file and the tool will manage it automatically. So the default config with `"padding": [
"=",
"."
]` it's ok, don't change it.

For your configuration issue, the `destination` must be a FQDN not an URL. Try to remove the `/recaptcha`. Also, maybe you want to remove the subdomain as well. Can't help you much with this ..

**Comment by jaredxx1** [comment]
I've found out why this happens. Maybe it will help others too.
Muraena does not replace the base64 value after the webpage is completely loaded. The reCaptcha iframe is inserted after DOMContentLoaded. How can I tweak this?

My partial solution is injecting the JS below:
`document.addEventListener('readystatechange', event => {

 if (event.target.readyState === "interactive") {
  var curInnerHTML = document.body.innerHTML;
  curInnerHTML = curInnerHTML.replace("base64_original", "base64_new");
  document.body.innerHTML = curInnerHTML;

 }

 if (event.target.readyState === "complete") {
  var curInnerHTML = document.body.innerHTML;
  curInnerHTML = curInnerHTML.replace("base64_original", "base64_new");
  document.body.innerHTML = curInnerHTML;
 }

});`

The problem is that click does not work after replacing.
Any ideas? I'm more interested in how to replace the base64 value after the complete page is loaded, and not inject JS.
