### ISSUE TITLE
Setting up a new template

### ISSUE THREAD

**Issue by infosecwatchman** [muraenateam/muraena#13]
Hello, I am trying to create a new template for collecting creds for Outlook (ie. live.com) I feel like I am very close to a solution, but seem to be stuck. I believe I have the correct search for the username and password, but I think I need some way to find the proper settings for the "crawler" configurations, what is the best way to find these setting?:
```
  "crawler": {
    "enabled": true,
    "depth": 2,
    "upto": 20,
    "externalOriginPrefix": "www-",
    "externalOrigins": []
  },
```
I have upload the HAR file from which I am pulling most of information, I have also uploaded what I have so far.
[public_view_outlook_Archive 19-06-20 08-13-18.txt](https://github.com/muraenateam/muraena/files/3310949/public_view_outlook_Archive.19-06-20.08-13-18.txt)
[public_view_muraena_outlook_live.com.txt](https://github.com/muraenateam/muraena/files/3310950/public_view_muraena_outlook_live.com.txt)

**Comment by GregorioSecurity** [comment]
@ohpe Any help would be greatly appreciated.
