### ISSUE TITLE
Emails are not loading in gmail

### ISSUE THREAD

**Issue by Avinashjaiswal420** [muraenateam/muraena#19]
Hello,

I have successfully setup and got gmail session but the problem is it is not loading any email. 
It is showing me the list of email in each folder but not loading any email. 

Please suggest.

Thanks

**Comment by ohpe** [comment]
There's some tweak to be done, but it's up to you.

**Comment by Avinashjaiswal420** [comment]
Hello,

Please help me with providing some steps for installing necrobrowser and
configuring it to work with Muraena.

Appreciate your help

Thanks
