### ISSUE TITLE
Replace header value

### ISSUE THREAD

**Issue by NoUseForANickname** [muraenateam/muraena#24]
Hi!

I need to replace the content of a response header (a batch of set-cookie). In the config file I saw that replacements with regex can be done in the body but I don't see how to do the same at header level. Is there a way to match-and-replace header values?

**Comment by ohpe** [comment]
Nope, that options it's missing at the moment.
I'll push an update soon to support it.

**Comment by NoUseForANickname** [comment]
I am working with a website that uses tons of values from cookies to work. The cookies are set to domain ".target.com", so they are not being  sent to my ".fake-target.com". I need to replace the scope of set-cookie from ".target.com" to ".fake-target.com".

**Comment by ohpe** [comment]
Alright, it was possible even before but the configuration was a bit confusing. I just pushed a new version with a slightly different configuration profile.
What is relevant for your part is the following:

```
...
      "response": {
        "header": [
          "Set-Cookie",
        ],
        "custom": [
          [
            "old-value",
            "new-value"
          ]
        ]
      }
...
```

`custom` section affects body and all the headers you add in the section above. Make sure you add `Set-Cookie` value, if you want to modify the cookies.

Ah, use the latest version [v0.2](https://github.com/muraenateam/muraena/releases/tag/v0.2).
