### ISSUE TITLE
Problem with Google

### ISSUE THREAD

**Issue by Bibleman1** [muraenateam/muraena#32]
I've been learning and trying to use this tool for weeks, works good tho but not too good with google, each time i proxy  through google and try to login, it doesn't let me, what happens is that after putting the email address of my test account, when i click next, the next button doesn't work, please i need assistance @ohpe @antisnatchor @almogmoyal

**Comment by ohpe** [comment]
That's because Google implemented some extra mechanisms to protect against Muraena & similar tools. 
There are still some bypasses but nothing I can share by now.

**Comment by Bibleman1** [comment]
Do we hope to see it fixed in the future update of the tool
