### ISSUE TITLE
not an issue / lack of documenation for config file 

### ISSUE THREAD

**Issue by bakree786** [muraenateam/muraena#40]
hi there team muraena i am trying to understand the code behind whats the role of crawler in code i see you also used this in config file [crawler]
    externalOriginPrefix = "www-"
    externalOrigins = [
      "*.anotherdomain.site",
      "example.dev"
    ]
what does it actually do any response would be highly appreciated from a student point of view thanks in advance  also if you can update wiki for config file parameter that would be great :-)

**Comment by antisnatchor** [comment]
hey, the externalOrigins are all the origins used by your phishing target. 

The crawler should discover most of them for you, and updated the config automatically.

For advanced usage, I recommend to manually investigate all the origins yourself, and then add the ones that the crawler might miss (especially if they are post-auth resources thsat can't be seen pre-auth)
