### ISSUE TITLE
[ISSUE] Runtime error: invalid memory address or nil pointer

### ISSUE THREAD

**Issue by magongo** [muraenateam/muraena#43]
I'm getting this error in linux at first connection by client : Why? 

` http: panic serving #MYCLIENTIP:PORT#: runtime error: invalid memory address or nil pointer dereference
goroutine 52 [running]:
net/http.(*conn).serve.func1(0xc00035c0a0)
        /usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x9fc460, 0x10e51e0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/muraenateam/muraena/module/tracking.(*Tracker).TrackRequest(0xc000074a20, 0xc0000fcf00, 0x853eb5d707b21cc6)
        /go/src/github.com/muraenateam/muraena/module/tracking/tracking.go:270 +0x2ca
github.com/muraenateam/muraena/proxy.(*MuraenaProxy).RequestProcessor(0xc0000a8550, 0xc0000fcf00, 0x0, 0x0)
        /go/src/github.com/muraenateam/muraena/proxy/handler.go:126 +0xa7
github.com/muraenateam/muraena/proxy.(*MuraenaProxyInit).Spawn.func1(0xc0000fcf00)
        /go/src/github.com/muraenateam/muraena/proxy/handler.go:385 +0x4a
github.com/muraenateam/muraena/proxy.(*ReverseProxy).ServeHTTP(0xc0000a8500, 0xb92a20, 0xc000120380, 0xc0000fcc00)
        /go/src/github.com/muraenateam/muraena/proxy/reverseproxy.go:200 +0x1dd
github.com/muraenateam/muraena/proxy.(*SessionType).HandleFood(0xc0002efc48, 0xb92a20, 0xc000120380, 0xc0000fcc00)
        /go/src/github.com/muraenateam/muraena/proxy/handler.go:495 +0x4d5
main.main.func1(0xb92a20, 0xc000120380, 0xc0000fcc00)
        /go/src/github.com/muraenateam/muraena/main.go:101 +0x63
net/http.HandlerFunc.ServeHTTP(0xc00000eb20, 0xb92a20, 0xc000120380, 0xc0000fcc00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x1111860, 0xb92a20, 0xc000120380, 0xc0000fcc00)
        /usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0000fc400, 0xb92a20, 0xc000120380, 0xc0000fcc00)
        /usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00035c0a0, 0xb94160, 0xc00029a480)
        /usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2884 +0x2f4`;

**Comment by ohpe** [comment]
Could you share the config?
