### ISSUE TITLE
Improve prompt helper

### ISSUE THREAD

**Issue by ohpe** [muraenateam/muraena#5]

**Comment by softdream1981** [comment]
Great

**Comment by softdream1981** [comment]
The proxy work but no victims or credentials printed. I got empty tables.

victims

┌────┬────┬────┬───────────────┬────────────┐
│ ID │ IP │ UA │ # Credentials │ # Requests │
├────┼────┼────┼───────────────┼────────────┤
└────┴────┴────┴───────────────┴────────────┘
> credentials

┌────┬─────┬───────┬──────┐
│ ID │ Key │ Value │ When │
├────┼─────┼───────┼──────┤
└────┴─────┴───────┴──────┘

**Comment by HsounaZinoubi** [comment]
@softdream1981
Can you make step by step tutorial on how to run it?
I compile it with no problem but. Get errors when launching it

**Comment by ohpe** [comment]
@softdream1981 basically you didn't instruct the tool to catch the credentials. Check and tune the `tracking` options in the configuration file.

@HsounaZinoubi if you have errors then you should file an issue, don't piggyback on others' issues please.

**Comment by imdj598** [comment]
Hi
I'va problem.
When start necrobrowser this messages appear

Wwaiting for commands on 0.0.0.0:8080 \m/
Auth Token: ada9f........

and don't continue!!
Where is problem
and
How to set Cookie?

**Comment by imdj598** [comment]
@ohpe hi!
I have problem to run necrobrowser 
Please guide me to run this tool
tnx
