### ISSUE TITLE
Not issue just wondering

### ISSUE THREAD

**Issue by soermejo** [muraenateam/muraena#53]
Wouldn't it be possible to cache non usefull requests so making it faster? 

For instance, allowing only non-static requests to pass through the proxy and the other being cached to the client

**Comment by ohpe** [comment]
That's actually a nice enhancement! I'll see how to implement a cache middleware .. unless you have already an idea and want to PR :)

**Comment by soermejo** [comment]
I don't even know if what I have said makes sense hahahah

Thinking again to it, browsers already cache those files in memory. 

And from what I can see (I'm testing it with a site) and those types of files are located in some subdomains or even other domains which don't even seems to pass through muraena but those requests goes directly there. This anyways doesn't seems to affect anything as it looks all normal.

Is this even right? Is it normal that muraena doesn't process those subdomains ?

For instance... Only requests made to site.com are changed to phishing.com but like c.site.com goes to c.site.com 

I tried the spider but I wasn't able to make it work.

**Comment by ohpe** [comment]
Ah you were basically trolling me? :)
The idea of caching can be interesting if muraena itself is not forwarding the request to any server but serves a cached request. This has its own benefits and downsides and definitely it is something that is not for "mainstream" usages. 

Regarding how muraena and subdomains works, it depends on how you configure it. But in super dummy mode: if you target `site.com`, even `*.site.com` is translated. While `anothersite.com` needs to be configured in the `crawler` section (`externalOrigins`)

**Comment by soermejo** [comment]
Regarding the crawler ok it works now, I was probably setting something wrong.

Yea that is what i was thinking about, but it seems like most part of the job is already done by browsers so static requests are cached and don't even starts anymore from the client.

and... why not mainstream? static requests dont change so don't see the points to let them pass trough every time.

**Comment by soermejo** [comment]
Another good feature would be support for multiple proxies so that each session has its own proxy coming from a list or something.

**Comment by soermejo** [comment]
Is it possible to have a chat with you on telegram?

**Comment by antisnatchor** [comment]
yes, channel here: bm9uY2VuZWZvdHRldW5jYXp6by5pdA==

**Comment by soermejo** [comment]
Ha ha ha
