### ISSUE TITLE
Stuck with the sudo ./muraena command

### ISSUE THREAD

**Issue by alora01** [muraenateam/muraena#54]
I want to first apologize for any grammatical errors i might make. I'm having this issues that i have been stuck on for a while now, (i am new to golang) when i used the make build command the build went to # cd $GOPATH/bin, i had to copy it to # cd $GOPATH/src/github.com/muraenateam/muraena. now i ran the # sudo ./muraena command and it gave me this.

NB: everything went fine until i ran the sudo ./muraena command

           ___   ____
        /' --;^/ ,-_\     \ | /                                                                        
       / / --o\ o-\ \\   --(_)--                                                                       
      /-/-/|o|-|\-\\|\\   / | \                                                                        
       '     |-|       /'-.-                                                                           
             |-|      |     \                                                                          
             |-|O     |      \                                                                         
             |-(\,__  |       \                                                                        
          ...|-|\--,\_|........\.--[ Muraena v1.3 (built for linux amd64 with go1.15.9) ]              
      ,;;;;;;;;;;;;;;;;;;;;;;;;,.  by @antisnatchor & @ohpe                                            
~~,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                         
~;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,  ______   ---------   _____     ------                           
  __________________________________________________________________________                           
                                                                                                       
Error reading configuration file : open : no such file or directory

**Comment by ohpe** [comment]
You need to provide a configuration file. Check the wiki here: https://github.com/muraenateam/muraena/wiki

**Comment by alora01** [comment]
this [config ](https://github.com/muraenateam/muraena/blob/master/config/config.toml) ??

**Comment by alora01** [comment]
i followed everything on the wiki and i still got the same errors @ohpe , i am trying to learn how this works, any help will be appreciated. I am a student.
