### ISSUE TITLE
missing b64 replace on Referer on request 

### ISSUE THREAD

**Issue by soermejo** [muraenateam/muraena#55]
Hi, i have noticed that if the fake domain is b64 encoded on "Referer" header on request to target site it is not replaced by the correct b64 domain so the fake domain is actually being sent in the Referer header if b64 encoded.

**Comment by ohpe** [comment]
Is the `Referer` header included in the list of HTTP headers to transform? Maybe provide an example so I can even debug it.

**Comment by soermejo** [comment]
Yes it is as default. What example ? I can show you a pic of the request being proxied with the  wrong domain on referer

![image](https://user-images.githubusercontent.com/21694707/120929244-98035680-c6e8-11eb-9a8d-886a9a716416.png)

**Comment by ohpe** [comment]
Proxied where? It's not clear what's the flow and what you want to do. If it is from your browser to muraena it still makes sense to have the phishing domain in it. 
But to me this doesn't seem a bug but more a problem of configuration .. MiTM Muraena to check what's going on (see here: https://github.com/muraenateam/muraena/wiki/Debugging)

**Comment by soermejo** [comment]
Proxied from muraena to target site. I used the env proxy settings. As you can see the domains are being replaced but that b64 on the Referer header no.

It is not from my browser. It shouldnt make any sense to proxy that from my browser as I can see from debug tool )

>But to me this doesn't seem a bug but more a problem of configuration
![image](https://user-images.githubusercontent.com/21694707/120929695-51166080-c6ea-11eb-984b-4e5e95349946.png)

**Comment by ohpe** [comment]
Thanks, well spotted @soermejo!

**Comment by soermejo** [comment]
Thanks to you for fixing the issue
