### ISSUE TITLE
failed to find any PEM data in certificate input

### ISSUE THREAD

**Issue by HsounaZinoubi** [muraenateam/muraena#6]
i get this error:
2019-05-17 12:03:12 !!!: Error binding Muraena on HTTPS: tls: failed to find any PEM data in certificate input
i use acme.sh to generate certs
it give me:
Your cert is in  /root/.acme.sh/example.com/example.com.cer
Your cert key is in  /root/.acme.sh/example.com/example.com.key
The intermediate CA cert is in  /root/.acme.sh/example.com/ca.cer
And the full chain certs is there:  /root/.acme.sh/example.com/fullchain.cer

so i did:
root@server:~/go/src/github.com/muraenateam/muraena/config# cp /root/.acme.sh/example.com/example.com.cer phishing-cert.pem
root@server:~/go/src/github.com/muraenateam/muraena/config# cp /root/.acme.sh/example.com/example.com.key phishing-key.pem
root@server:~/go/src/github.com/muraenateam/muraena/config# cp /root/.acme.sh/example.com/ca.cer phishing-rootCA.pem

i run :
./muraena -config config/config.json
i get this:

root@server:~/go/src/github.com/muraenateam/muraena# ./muraena -config config/config.json

           ___   ____
        /' --;^/ ,-_\     \ | /
       / / --o\ o-\ \\   --(_)--
      /-/-/|o|-|\-\\|\\   / | \
       '     |-|       /'-.-
             |-|      |     \
             |-|O     |      \
             |-(\,__  |       \
          ...|-|\--,\_|........\.--[ Muraena v0.1.2 (built for linux amd64 with go1.12.4) ]
      ,;;;;;;;;;;;;;;;;;;;;;;;;,.  by @antisnatchor & @ohpe
~~,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,  ______   ---------   _____     ------
  __________________________________________________________________________

2019-05-17 12:03:11 inf: [crawler] Starting exploration of proxiedwebsite.com (crawlDepth:2 crawlMaxReq: 20), just a few seconds...
> █
2019-05-17 12:03:12 inf: [crawler] Domain crawling stats:

┌──────────────────┬─────┐
│     Domains      │  #  │
├──────────────────┼─────┤
│ External domains │ 0   │
│ Subdomains       │ 0   │
│ ---------------- │ --- │
│ Unique domains   │ 0   │
└──────────────────┴─────┘
2019-05-17 12:03:12 imp: [tracker] loaded successfully
2019-05-17 12:03:12 inf: Proxy destination: *.proxiedwebsite.com
2019-05-17 12:03:12 inf: Processed 0 domains to transform, 0 are wildcards
2019-05-17 12:03:12 inf: Muraena Reverse Proxy waiting for food on HTTPS...
[ example.com ] ==> [ proxiedwebsite.com ]
2019-05-17 12:03:12 !!!: Error binding Muraena on HTTPS: tls: failed to find any PEM data in certificate input
root@server:~/go/src/github.com/muraenateam/muraena#

**Comment by ohpe** [comment]
Please, read here https://github.com/muraenateam/muraena/wiki/Setup for the TLS configuration setup.
