### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by Ondrik8** [muraenateam/muraena#62]
`
2021-10-09 12:08:28 !!!: redis dial tcp 127.0.0.1:6379: connectex: No connection could be made because the target machine actively refused it.
`
![Screenshot_3](https://user-images.githubusercontent.com/59111771/136652181-2e03a5c8-de07-4aa8-9587-13214630504f.png)

![Screenshot_1](https://user-images.githubusercontent.com/59111771/136652252-16ccde15-04fe-450d-b067-17493c0314fe.png)

**Comment by staynew01** [comment]
> sorry, I didn’t read the instructions here)
> 
> https://github.com/muraenateam/muraena/tree/master/docs

Hello, could you please tell me how you fixed your problem? I amhaving the same issue but I did not understand it with the link you posted here. Tried to fix the problem but it wont work.

Kind regards
