### ISSUE TITLE
Error unmarshalling JSON configuration file ./config/config.toml: invalid character 'p' looking for beginning of value

### ISSUE THREAD

**Issue by 3hxks** [muraenateam/muraena#64]
I use the default config.toml can not run properly, please help

`[root@C20220114153649 muraena]# ./muraena666 -config ./config/config.toml 

           ___   ____
        /' --;^/ ,-_\     \ | /
       / / --o\ o-\ \\   --(_)--
      /-/-/|o|-|\-\\|\\   / | \
       '     |-|       /'-.-
             |-|      |     \
             |-|O     |      \
             |-(\,__  |       \
          ...|-|\--,\_|........\.--[ Muraena v0.1.4 (built for linux amd64 with go1.16.12) ]
      ,;;;;;;;;;;;;;;;;;;;;;;;;,.  by @antisnatchor & @ohpe
~~,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,  ______   ---------   _____     ------
  __________________________________________________________________________

Error unmarshalling JSON configuration file ./config/config.toml: invalid character 'p' looking for beginning of value
[root@C20220114153649 muraena]# 
`

**Comment by ohpe** [comment]
Please download latest Muraena. Your version is outdated, see here: https://github.com/muraenateam/muraena/releases
