### ISSUE TITLE
Error reading configuration file : open : no such file or directory

### ISSUE THREAD

**Issue by jacmatmar** [muraenateam/muraena#68]
I am trying to configure muraena in kali linux & this is how far I've gotten. I tried to search for a solution to this but still come up empty handed. Any ideas?

![Screenshot (14) (1)](https://user-images.githubusercontent.com/99425386/156901440-0ec77d9a-74f9-4505-87d9-703b81a049bb.png)

**Comment by Ondrik8** [comment]
./muraena -h

./muraena -config /folder/config.toml

**Comment by jacmatmar** [comment]
> ./muraena -h
> 
> ./muraena -config /folder/config.toml

The first command went through but the second came up with the same message. 
![Screenshot (15)](https://user-images.githubusercontent.com/99425386/156948379-9f1f6699-c903-41e0-a8b1-9694a9f734ac.png)

**Comment by ohpe** [comment]
maybe you don't have a path `/folder/config.toml`. Try to point `-config` to an existing configuration file.
