### ISSUE TITLE
Google Mobile Prompts/Push Notifications

### ISSUE THREAD

**Issue by stackerofwheat** [muraenateam/muraena#7]
google config is able to handle SMS 2fa beautifully however not mobile push notifications sent when new logins are detected. Google sends mobile prompts to android devices(not sure about ios) when detecting a new login, however when i tap the device screen to verify the login the screen just hangs. There is a workaround because I can tap "try another way" to receive an SMS message but it still raises suspicion.

**Comment by ohpe** [comment]
We can't provide support for this scenario. 
If you have a specific bug or a feature request, then you're more than welcome.
