### ISSUE TITLE
Can't install latest Muraena with go install ...

### ISSUE THREAD

**Issue by 10tecs** [muraenateam/muraena#72]
Hello. Title basically, thanks for any hints.

```
go install github.com/muraenateam/muraena@v0.1.7
go: github.com/muraenateam/muraena@v0.1.7: github.com/muraenateam/muraena@v0.1.7: invalid version: unknown revision v0.1.7
```
and @latest will just pull 0.1.4, probably because:

```
$ go list -m -versions github.com/muraenateam/muraena
github.com/muraenateam/muraena v0.1.1 v0.1.2 v0.1.3 v0.1.4
```

**Comment by Chomikmarkus** [comment]
Have same issue pulls version v 0.1.4

**Comment by 10tecs** [comment]
I manually downloaded and unzipped 1.7 in the ~/go/bin folder, then in muraena-master: 
make build
cd build
./muraena

good luck champ.

**Comment by Chomikmarkus** [comment]
> 

Thanks worked for me!!!
