### ISSUE TITLE
Necrobrowser 

### ISSUE THREAD

**Issue by Chomikmarkus** [muraenateam/muraena#73]
With current version of muraena, do i need to install necrobrowser separately on machine?

**Comment by elite-user** [comment]
what ever is best for you, you can use on the same machine or different machine, so as the doc said. Did you get muraena up and running?

**Comment by Chomikmarkus** [comment]
root@ubuntu-s-1vcpu-2gb-fra1-01:/opt/necrobrowser# npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> puppeteer@7.1.0 install /opt/necrobrowser/node_modules/puppeteer
> node install.js

Downloading Chromium r848005 - 138.2 Mb [====================] 100% 0.0s
Chromium (848005) downloaded to /opt/necrobrowser/node_modules/puppeteer/.local-chromium/linux-848005
npm WARN @muraenateam/puppeteer-cluster@0.2.1 requires a peer of puppeteer@^1.5.0 || ^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN necrobrowser@0.1.1 license should be a valid SPDX license expression
npm WARN The package @muraenateam/puppeteer-cluster is included as both a dev and production dependency.
npm WARN The package chalk is included as both a dev and production dependency.
npm WARN The package express is included as both a dev and production dependency.
npm WARN The package jest is included as both a dev and production dependency.
npm WARN The package morgan is included as both a dev and production dependency.
npm WARN The package node-eval is included as both a dev and production dependency.
npm WARN The package puppeteer is included as both a dev and production dependency.
npm WARN The package puppeteer-extra is included as both a dev and production dependency.
npm WARN The package puppeteer-extra-plugin-stealth is included as both a dev and production dependency.
npm WARN The package redis is included as both a dev and production dependency.
npm WARN The package shortid is included as both a dev and production dependency.
npm WARN The package toml is included as both a dev and production dependency.
npm WARN The package typescript is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 654 packages from 432 contributors and audited 655 packages in 42.322s

29 packages are looking for funding
  run `npm fund` for details

found 54 vulnerabilities (1 low, 43 moderate, 10 high)
  run `npm audit fix` to fix them, or `npm audit` for details
root@ubuntu-s-1vcpu-2gb-fra1-01:/opt/necrobrowser# node necrobrowser.js
error: check that extrusionPath and profilesPath are existing directories
root@ubuntu-s-1vcpu-2gb-fra1-01:/opt/necrobrowser#

**Comment by Chomikmarkus** [comment]
I have opened issue also to necrobrowser repo! It seems like lot dependancies are deprecated and it just refuses to run! 
I got muraena itself to but  no creds are harvested, what may also be config file error!

**Comment by Chomikmarkus** [comment]
![Screenshot_20220404-015119_Chrome](https://user-images.githubusercontent.com/92059377/161452220-cc5f283d-b521-46fd-ac12-7f2c280312ad.jpg)

**Comment by Chomikmarkus** [comment]
recaptcha cannot be bypassed?

**Comment by Chomikmarkus** [comment]
And have issue with creditential harvesting, useragent and ip is collected but no login data

**Comment by Chomikmarkus** [comment]
So everything else seems to work beside necrobrowser and recaptcha transform!

**Comment by Chomikmarkus** [comment]
Works now!

**Comment by pentest01** [comment]
How did you get necrobrowser to work?

on same machine or different machine??
