### ISSUE TITLE
Setup successful - but website shows blank page

### ISSUE THREAD

**Issue by elite-user** [muraenateam/muraena#74]
I cannot load my proxied website even though I think I've setup everything correctly.

Setup with ./muraena --config config/config.toml 

this is a screenshot

[https://github.com/elite-user/errors/blob/main/muraena.png](url)

and here is my log file 

https://github.com/elite-user/errors/blob/main/muraena.log

i have redis installed. Your help will be so much helpful.

**Comment by ohpe** [comment]
You have both watchdog filtering you and TLS not configured to support unknown CA.

**Comment by elite-user** [comment]
How do i fix this pls.

**Comment by horllste** [comment]
start from the beginning, you will see what you missed
