### ISSUE TITLE
Tracking patterns

### ISSUE THREAD

**Issue by Chomikmarkus** [muraenateam/muraena#79]
How tracking patterns are working!  Cannot fully understand it. What parameters should be used in order to track input?
What are meaning of end =,matching= etc? 

[[tracking.patterns]]
    end = "&"
    label = "LoginForm_password"
    matching = "password"
    start = "password="

  [tracking.urls]
    matching = "password"end/api/v1/account/login"]
    start = "password="myymalat/"]

[t[tracking.urls]
  skauthSession = ["/backend/api/v1/account/login"]

**Comment by Chomikmarkus** [comment]
Got it clear ;) but still have issues with necrobrowser

**Comment by Onyinye10** [comment]
Please how did you fix the tracking patterns
