### ISSUE TITLE
O365

### ISSUE THREAD

**Issue by kwekudumebi** [muraenateam/muraena#80]
Trying to proxy office.com but immediately I enter my username, I am taken to a page that says unable to complete the 
<img width="1440" alt="Screen Shot 1401-01-28 at 11 09 40" src="https://user-images.githubusercontent.com/103643645/163712139-4828186f-5c12-4f71-88d0-cd4307a02575.png">
request here is my configuration, I'm guessing some settings need to be changed in the headers or elsewhere, can someone please point me in the right direction.<img width="1440" alt="Screen Shot 1401-01-28 at 11 09 40" src="https://user-images.githubusercontent.com/103643645/163712072-6109eaa2-d401-4149-9e14-442538b6e50a.png">

**Comment by kwekudumb** [comment]
<img width="1440" alt="Screen Shot 1401-01-28 at 11 08 21" src="https://user-images.githubusercontent.com/103643645/163712219-41b746c4-9f74-4601-a497-d4c8c216a784.png">
Here is the error page i get after entering username

**Comment by ohpe** [comment]
This should be fixed in latest release 1.8.
