### ISSUE TITLE
Removing integrity tags

### ISSUE THREAD

**Issue by farangpal** [muraenateam/muraena#83]
Is there anyway to remove the checksum tags?
Example: 
```
integrity="sha256-5qo1jMHhtxE84sy1AFB3N3NNSdT8zX9l7rJyM9li2/0= sha512-36T0HKUOccAaCBmtM6zc0eOqAEtL49ApGvRzwvbu/lGyqcfl1L8Lgu51rLJwLS1337KP/Hgl9Rksij9JDRHU1Q=="
```
Would like to replace it with
```
integrity=" "
```

I'm getting a blank page on the login page of the site I'm experimenting with, not sure if that will solve the issue.

 I'm trying to do Discord, but I'm getting a blank page on the login page, I read somewhere that removing the integrity might solve the issue.

**Comment by farangpal** [comment]
Fixed it, I got the page to work

**Comment by farangpal** [comment]
Ok, so I solved that issue, I tried to login with my account to see if everything worked, it did, except one thing. 

When I tried to login it detected the location as new and required an email to verify this new location.  Anyway to circumvent this?

**Comment by ohpe** [comment]
Nope, that goes beyond the goal of this tool.
