### ISSUE TITLE
How to proxy domains like https://abc.xyz.domain.com

### ISSUE THREAD

**Issue by ssl-user-en** [muraenateam/muraena#84]
I was wondering if anyone could help me with proxying any domain like https://abc.xyz.domain.com cos the tool automatically transforms the domain into https://(wild*card).domain.com whereas it should change the domain to https://(wild*card).xyz.domain.com

Any help would be much appreciated to understand the issue.

**Comment by ohpe** [comment]
You can now set in your config: `destination = "xyz.domain.com` to cover your scenario.
Keep in mind that wildcard TLS certificates needs to be generated accordingly ..
