### ISSUE TITLE
CEST !!! Error binding Muraena on HTTPS: tls: private key does not match public key

### ISSUE THREAD

**Issue by staynew01** [muraenateam/muraena#87]
Hello,
I tried to run Muraena but everytime the error ''CEST !!! Error binding Muraena on HTTPS: tls: private key does not match public key'' appears. Any ideas how I can fix that?

**Comment by ohpe** [comment]
Ensure your TLS configuration is set properly:
https://github.com/muraenateam/muraena/blob/v1.9/config/config.toml#L143
