### ISSUE TITLE
Trouble with make build on Kali Linux

### ISSUE THREAD

**Issue by beccag123** [muraenateam/muraena#88]
Hello, running the most recent version of kali, followed all the steps correctly, Go is installed correctly and all paths are correctly configured etc. However when I go to the directory and run make build, it likes it will will work but then throws the following error:
`mkdir -p ./build/
env GO111MODULE=on go get -d ./
rm -f -f ./build/muraena
go build -o ./build/muraena .
module/crawler/crawler.go:10:2: cannot find package "." in:
	/root/.go/pkg/mod/github.com/muraenateam/muraena@v0.1.4/vendor/github.com/ditashi/jsbeautifier-go/jsbeautifier
core/helper.go:12:2: cannot find package "." in:
	/root/.go/pkg/mod/github.com/muraenateam/muraena@v0.1.4/vendor/github.com/dsnet/compress/brotli
log/log.go:9:2: cannot find package "." in:
	/root/.go/pkg/mod/github.com/muraenateam/muraena@v0.1.4/vendor/github.com/evilsocket/islazy/log
main.go:16:2: cannot find package "." in:
	/root/.go/pkg/mod/github.com/muraenateam/muraena@v0.1.4/vendor/github.com/evilsocket/islazy/tui
module/crawler/crawler.go:12:2: cannot find package "." in:
	/root/.go/pkg/mod/github.com/muraenateam/muraena@v0.1.4/vendor/github.com/gocolly/colly
proxy/handler.go:13:2: cannot find package "." in:
	/root/.go/pkg/mod/github.com/muraenateam/muraena@v0.1.4/vendor/github.com/logrusorgru/aurora
module/tracking/tracking.go:16:2: cannot find package "." in:
	/root/.go/pkg/mod/github.com/muraenateam/muraena@v0.1.4/vendor/github.com/lucasjones/reggen
session/prompt.go:10:2: cannot find package "." in:
	/root/.go/pkg/mod/github.com/muraenateam/muraena@v0.1.4/vendor/github.com/manifoldco/promptui
session/config.go:13:2: cannot find package "." in:
	/root/.go/pkg/mod/github.com/muraenateam/muraena@v0.1.4/vendor/github.com/pkg/errors
module/necrobrowser/necrobrowser.go:7:2: cannot find package "." in:
	/root/.go/pkg/mod/github.com/muraenateam/muraena@v0.1.4/vendor/gopkg.in/resty.v1
module/crawler/crawler.go:14:2: cannot find package "." in:
	/root/.go/pkg/mod/github.com/muraenateam/muraena@v0.1.4/vendor/mvdan.cc/xurls
make: *** [Makefile:15: build] Error 1
`

and ideas on the problem or what I can do to fix? thank you

**Comment by George152-max** [comment]
Hit me up on telegram @OkorohWorld
