### ISSUE TITLE
What am i doing wrong 127.0.0.1:6379

### ISSUE THREAD

**Issue by lhost25** [muraenateam/muraena#89]
I keep getting this error message after setting my config. Kindly please assist me.

Maybe my Redis isn't working but I don't know how to go about the Redis to work. Please I need someone to walk me through this process thoroughly.

@ohpe @antisnatchor

![Screenshot 2022-11-30 at 2 10 53 AM](https://user-images.githubusercontent.com/87344213/204683470-1b52582d-ffa0-4c31-b5b6-5c258ee66a6c.png)

**Comment by ohpe** [comment]
It's your redis not working, make sure it's up and running.
