### ISSUE TITLE
Feature request: add session

### ISSUE THREAD

**Issue by infosecwatchman** [muraenateam/muraena#9]
Not sure how to do this, but the credentials and cookies should save across server runs.

**Comment by ohpe** [comment]
Are you asking for a session feature?

**Comment by GregorioSecurity** [comment]
Yes, the creds need to save in a db somewhere so even if you close muraena you still keep your creds.

**Comment by antisnatchor** [comment]
Thanks for waiting @infosecwatchman .
This is now implemented via Redis.
