### ISSUE TITLE
getting redirected to the original website

### ISSUE THREAD

**Issue by alias-64** [muraenateam/muraena#97]
here's my log:

2024-03-15 18:32:08 inf: Connected to Redis
15 Mar 24 18:32 UTC inf Muraena is alive on 0.0.0.0:443
[ mysite.xyz ] ==> [ targetsite.com ]

(EDIT) github messed up the config format so here's the config file:
https://pastebin.com/A6eH9yLA

**Comment by alias-64** [comment]
github messed up the config format so here's the config file
https://pastebin.com/A6eH9yLA

**Comment by ohpe** [comment]
It might be you do not transform headers such as `Location`, etc.
review carefully your config file.
