### ISSUE TITLE
Instagram gets stuck

### ISSUE THREAD

**Issue by saakkaas** [muraenateam/muraena#98]
18 Mar 24 06:57 EDT ver Patched HTTP Referer to https://www.instagram.com/
18 Mar 24 06:57 EDT ver Patched HTTP Origin to https://www.instagram.com
18 Mar 24 06:57 EDT ver Sender IP not found in headers, falling back to RemoteAddr
18 Mar 24 06:57 EDT ver [     ][127.0.0.1] [POST][https://www.instagram.com/ajax/qm/]

**Comment by Goldenman187** [comment]
Can somebody help me get my instagram back.please

**Comment by ohpe** [comment]
Maybe it's not the agent stuck but the config not proxying all the origins.
Check your browser's console

**Comment by saakkaas** [comment]
> Maybe it's not the agent stuck but the config not proxying all the origins. Check your browser's console

Thanks, I will fix it, and one more question.

war necrobrowser Error reading profile file : open : no such file or directory

What do I have to write for necrobrowser profile path in config file ? I changed a lot, but the same error still exists

**Comment by ohpe** [comment]
See the docs here for configuring Necrobrowser in Muraena: https://muraena.phishing.click/modules/necrobrowser.
and here for running Necrobrowser: https://necrobrowser.phishing.click/
